# Generated by Django 3.2.7 on 2021-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='front',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Top'), (2, 'Secondary')], default=0),
        ),
    ]
